title: Roxana Zaminpeyma
email: roxaneh.zaminpeyma@mail.mcgill.ca
description: >- # this means to ignore newlines until "baseurl:"
Welcome to my personal website. Here you can find my latest community projects and a little more about me. Look around to find out more!


remote_theme: andrewbanchich/forty-jekyll-theme
url: roxanehzaminpeyma.github.io
baseurl: /
